apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ic-webapp
    env: prod
  name: ic-webapp
  namespace: ic-webapp
spec:  
  selector:
    app: ic-webapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080 
